ta404:
  application:
    name: ta404
    version: 5.3.2-RELEASE
spring:
  profiles:
    active: dev,datasource,websecurity
  application:
    name: ${ta404.application.name}
  main:
    allow-bean-definition-overriding: true
  banner:
    location: banner.txt
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 20MB
  jackson:
    time-zone: GMT+8:00
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    parser:
      ALLOW_SINGLE_QUOTES: true

server:
  port: 8081
  servlet:
    session:
      timeout: 7200s
    context-path: /ta404
